apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecrpdeployment
  labels:
    app: ecrpdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecrpdeployment
  template:
    metadata:
      labels:
        app: ecrpdeployment
    spec:
      containers:
        - name: ecrpdeployment
          image: 861276106382.dkr.ecr.us-east-1.amazonaws.com/ecr-repoimg1:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5002